"""Parity: jobcore must reproduce naukri's scoring EXACTLY.

``golden_scores.json`` was generated by running the PRISTINE
``naukri_server`` scoring modules (commit 0021d82, before the shim landed)
over 179 inputs plus the full 88-skill / 150-alias table. If any number,
string or alias in here drifts, the extraction changed behaviour and the
live job server would start scoring differently — so these tests fail loudly
rather than approximately.

Regenerating this file is NOT a way to make a failure go away. It is only
valid when the scoring rules are deliberately changed, in which case naukri
and jobcore must be re-measured together.
"""

import ast
import json
from pathlib import Path

import pytest

from jobcore import (
    SKILL_ALIASES,
    DEFAULT_TAXONOMY,
    Salary,
    compute_fit_score,
    normalize_skill,
    parse_skills,
    score_location,
    score_salary,
    score_work_mode,
)

GOLDEN_PATH = Path(__file__).parent / "golden_scores.json"


@pytest.fixture(scope="session")
def golden():
    # A missing or empty corpus must be an ERROR, never an empty parametrize
    # that silently passes zero cases.
    assert GOLDEN_PATH.is_file(), f"golden corpus missing: {GOLDEN_PATH}"
    data = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))
    assert data, "golden corpus is empty"
    return data


def _load():
    """Module-import-time load so parametrize can enumerate the cases."""
    return json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))


_G = _load()

# Guard the parametrize sources themselves: an empty list would make every
# test below vacuously pass.
for _section in (
    "normalize_skill", "parse_skills", "salary", "salary_nonstring",
    "score_location", "score_work_mode", "score_salary", "compute_fit_score",
):
    assert _G.get(_section), f"golden section {_section!r} is empty"


class TestNormalizeSkillParity:
    @pytest.mark.parametrize("raw,expected", _G["normalize_skill"])
    def test_matches_naukri(self, raw, expected):
        assert normalize_skill(raw) == expected


class TestParseSkillsParity:
    @pytest.mark.parametrize("raw_repr,expected", _G["parse_skills"])
    def test_matches_naukri(self, raw_repr, expected):
        # literal_eval, not eval: the corpus holds only Python literals.
        raw = ast.literal_eval(raw_repr)
        assert sorted(parse_skills(raw)) == expected


class TestSalaryParity:
    @pytest.mark.parametrize("case", _G["salary"], ids=lambda c: c["raw_in"] or "empty")
    def test_matches_naukri(self, case):
        s = Salary.from_string(case["raw_in"])
        assert s.min_lakhs == case["min_lakhs"]
        assert s.max_lakhs == case["max_lakhs"]
        assert s.raw == case["raw"]
        assert s.is_disclosed == case["is_disclosed"]
        assert s.midpoint == case["midpoint"]
        assert s.compare_to_ctc(15) == case["compare_to_ctc_15"]
        assert s.compare_to_ctc("25") == case["compare_to_ctc_str25"]
        assert s.compare_to_ctc("not-a-number") == case["compare_to_ctc_bad"]
        assert s.market_position(12.0) == case["market_position_12"]
        assert s.market_position(30.0) == case["market_position_30"]

    @pytest.mark.parametrize("case", _G["salary_nonstring"])
    def test_nonstring_input_matches_naukri(self, case):
        raw_repr, mn, mx, raw, disclosed = case
        s = Salary.from_string(ast.literal_eval(raw_repr))
        assert (s.min_lakhs, s.max_lakhs, s.is_disclosed) == (mn, mx, disclosed)
        assert s.raw == raw


class TestBonusHelperParity:
    @pytest.mark.parametrize("job_loc,prof_loc,expected", _G["score_location"])
    def test_location(self, job_loc, prof_loc, expected):
        assert score_location(job_loc, prof_loc) == expected

    @pytest.mark.parametrize("mode,expected", _G["score_work_mode"])
    def test_work_mode(self, mode, expected):
        assert score_work_mode(mode) == expected

    @pytest.mark.parametrize("job_sal,ctc,expected", _G["score_salary"])
    def test_salary(self, job_sal, ctc, expected):
        assert score_salary(
            ast.literal_eval(job_sal), ast.literal_eval(ctc)
        ) == expected


class TestComputeFitScoreParity:
    @pytest.mark.parametrize(
        "case", _G["compute_fit_score"], ids=range(len(_G["compute_fit_score"]))
    )
    def test_matches_naukri(self, case):
        kwargs = json.loads(case["input"])
        for key in ("job_skills", "profile_skills"):
            if key in kwargs and kwargs[key] is not None:
                kwargs[key] = set(kwargs[key])
        assert compute_fit_score(**kwargs) == case["output"]


class TestTaxonomyParity:
    def test_canonical_count_unchanged(self):
        assert DEFAULT_TAXONOMY.canonical_count == _G["taxonomy"]["canonical_count"]

    def test_alias_count_unchanged(self):
        assert DEFAULT_TAXONOMY.alias_count == _G["taxonomy"]["alias_count"]

    def test_every_alias_identical(self):
        """The crown jewel, entry by entry — not just the totals."""
        ours = {k: sorted(v) for k, v in SKILL_ALIASES.items()}
        assert ours == _G["taxonomy"]["aliases"]
